#######################
# pad_tester Makefile #
#######################

NAME=pad_tester
BOARD=GAMEBLADE
MODEL=xmmc

SPINDIR=./spin

HDRS=\
	 pins.h\
	 vga.h\
	 gamepad.h

OBJS=\
	 pins.o \
	 vga.o \
	 gamepad.o \
	 pad_tester.o

CFLAGS = -Os -DPROPELLER_GCC

include ../common/common.mk
