######################
# segloader Makefile #
######################

NAME=rock_paper_scissors
BOARD=GAMEBLADE
MODEL=xmmc

SPINDIR=./spin

HDRS=\
	 gamepad.h\
	 pins.h\
	 vga_text.h

OBJS=\
	 gamepad.o\
	 pins.o\
	 vga_text.o\
	 VGA_firmware.o\
	 rock_paper_scissors.o

CFLAGS = -Os -DPROPELLER_GCC

include ../common/common.mk
